---
title: "Hello R"
author: "Cameron Nathan"
date: "9/3/24"
output: html_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

(A data frame with 1846 rows and 3 variables:

dataset: indicates which dataset the data are from

x: x-values

y: y-values)


### Exercise 2

```{r plot-dino, fig.height=4, fig.width=7}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

```{r plot-star, fig.height=4, fig.width=4}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) + 
  geom_point()

```

The correlation coefficient between x and y is a different value than the r of dino
 
```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))

```

### Exercise 4

```{r plot-circle, fig.height=5, fig.width=5}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) + 
  geom_point()

```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))

```

### Exercise 5

```{r fig.height=8, fig.width=8}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
geom_point()+
facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
theme(legend.position = "none")
```


```{r}
datasaurus_dozen %>%
group_by(dataset) %>%
summarize(r = cor(x, y)) %>%
print(13)
```



